### ISSUE TITLE
Single Dockerfile.template by using the RESIN_ARCH template variable

### ISSUE THREAD

**Issue by majorz** [resin-io-projects/balena-rust-hello-world#12]
It is possible to provide a single `Dockerfile.template` instead of three almost identical files by using `RESIN_ARCH` and modifying the `uname` trick we are using for armv7 and armv6.

**Comment by cyplo** [comment]
Very good point !

**Comment by majorz** [comment]
I will PR this in a bit. There was a bug with not starting the real hello application the first time (but the fake for dependencies), and it took me some time to figure it out.
