### ISSUE TITLE
I failed to run this repo using a raspberry-pi2 project

### ISSUE THREAD

**Issue by tjamet** [resin-io-projects/balena-rust-hello-world#5]
Depending on which host the compilation ends on, I get a `rustup: unknown CPU type: armv8l` on `arm03` or `arm01` builders when running the `RUN curl -sSf https://static.rust-lang.org/rustup.sh | sh` step

Here is the output I get:
```
[Info]  Starting build for raspot, user [REDACTED]
[Info]  Dashboard link: https://dashboard.resin.io/apps/[REDACTED]/devices
[Info]  Building on arm03
[Info]  Pulling previous images for caching purposes...
[Success]  Successfully pulled cache images
[main]  Step 1/8 : FROM resin/raspberry-pi2-debian
[main]   ---> f761ebbeb884
[main]  Step 2/8 : ENV INITSYSTEM on
[main]  Using cache
[main]   ---> 67603079ff2c
[main]  Step 3/8 : RUN apt-get -q update && apt-get install -yq --no-install-recommends 	build-essential curl file 	&& apt-get clean && rm -rf /var/lib/apt/lists/*
[main]  Using cache
[main]   ---> de3fdb36a33f
[main]  Step 4/8 : WORKDIR /usr/src/app
[main]  Using cache
[main]   ---> 5bf5e3280dcf
[main]  Step 5/8 : RUN curl -sSf https://static.rust-lang.org/rustup.sh | sh
[main]   ---> Running in 68eaa52d0eac
[main]  rustup: unknown CPU type: armv8l
[main]
[main]  Removing intermediate container 68eaa52d0eac
[main]  The command '/bin/sh -c curl -sSf https://static.rust-lang.org/rustup.sh | sh' returned a non-zero code: 1
```
any idea how to get rust and cargo to work in resin builders?

Thank you

**Comment by floion** [comment]
@majorz maybe you have some pointers here?

**Comment by zrzka** [comment]
@tjamet I did update `master` few minutes ago. Here's what I have to do for RPi 3 B+ for example.

https://github.com/resin-io-projects/resin-rust-hello-world/blob/master/Dockerfile.template#L26-L31

Does this help?

**Comment by cyplo** [comment]
There was an update recently ( #10 ) that adds support for more architectures - could you check @tjamet ? Thanks so much !

**Comment by majorz** [comment]
I verified this works now. Closing.
